export enum NetworkEvents {
  JOINED_ROOM = "JOINED_ROOM",
  JOIN_ERROR = "JOIN_ERROR",
  ROOM_ERROR = "ROOM_ERROR",
  RECONNECT_ERROR = "RECONNECT_ERROR",
  LEFT_ROOM = "LEFT_ROOM",
  ON_MESSAGE = "ON_MESSAGE",
  ROOM_STATE_CHANGED = "ROOM_STATE_CHANGED",
}
